apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-sql
  namespace: envoy-proxy
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: go-auth-ms
data:
  init.sql: |
    USE authdb;

    CREATE TABLE IF NOT EXISTS Auth (
        ID          BIGINT       NOT NULL AUTO_INCREMENT,
        Token       VARCHAR(512) NOT NULL,
        Description TEXT,
        PRIMARY KEY (ID)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
