apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: envoy-proxy
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: go-auth-ms
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
