apiVersion: v1
kind: Secret
metadata:
  name: auth-db-secret
  namespace: envoy-proxy
  labels:
    app.kubernetes.io/part-of: go-auth-ms
type: Opaque
stringData:
  postgres-user:     authuser
  postgres-password: authpass
  postgres-db:       authdb
